trigger: ["master"]
pr: ["master"]

resources:
  repositories:
    - repository: templates
      type: github
      name: alecmocatta/azure-pipeline-templates
      endpoint: alecmocatta

jobs:
- template: rust.yml@templates
  parameters:
    endpoint: alecmocatta
    default:
      rust_toolchain: nightly
      rust_lint_toolchain: nightly-2019-09-13
      rust_flags: ''
      rust_features: 'no_alloc;no_alloc distribute_binaries'
      rust_target_check: ''
      rust_target_build: ''
      rust_target_run: ''
      constellation_test_iterations: '50'
    matrix:
      # windows:
      #   imageName: 'vs2017-win2016'
      #   rust_target_run: 'x86_64-pc-windows-msvc i686-pc-windows-msvc' # currently broken building crate-type=lib: x86_64-pc-windows-gnu i686-pc-windows-gnu
      mac0:
        imageName: 'macos-10.13'
        rust_target_run: 'x86_64-apple-darwin' # i686-apple-darwin'
      mac1:
        imageName: 'macos-10.13'
        rust_target_run: 'x86_64-apple-darwin' # i686-apple-darwin'
      mac2:
        imageName: 'macos-10.13'
        rust_target_run: 'x86_64-apple-darwin' # i686-apple-darwin'
      mac3:
        imageName: 'macos-10.13'
        rust_target_run: 'x86_64-apple-darwin' # i686-apple-darwin'
      mac4:
        imageName: 'macos-10.13'
        rust_target_run: 'x86_64-apple-darwin' # i686-apple-darwin'
      mac5:
        imageName: 'macos-10.13'
        rust_target_run: 'x86_64-apple-darwin' # i686-apple-darwin'
      mac6:
        imageName: 'macos-10.13'
        rust_target_run: 'x86_64-apple-darwin' # i686-apple-darwin'
      mac7:
        imageName: 'macos-10.13'
        rust_target_run: 'x86_64-apple-darwin' # i686-apple-darwin'
      mac8:
        imageName: 'macos-10.13'
        rust_target_run: 'x86_64-apple-darwin' # i686-apple-darwin'
      mac9:
        imageName: 'macos-10.13'
        rust_target_run: 'x86_64-apple-darwin' # i686-apple-darwin'
      linux0:
        imageName: 'ubuntu-16.04'
        rust_target_run: 'x86_64-unknown-linux-gnu' # i686-unknown-linux-gnu x86_64-unknown-linux-musl i686-unknown-linux-musl'
      linux1:
        imageName: 'ubuntu-16.04'
        rust_target_run: 'x86_64-unknown-linux-gnu' # i686-unknown-linux-gnu x86_64-unknown-linux-musl i686-unknown-linux-musl'
      linux2:
        imageName: 'ubuntu-16.04'
        rust_target_run: 'x86_64-unknown-linux-gnu' # i686-unknown-linux-gnu x86_64-unknown-linux-musl i686-unknown-linux-musl'
      linux3:
        imageName: 'ubuntu-16.04'
        rust_target_run: 'x86_64-unknown-linux-gnu' # i686-unknown-linux-gnu x86_64-unknown-linux-musl i686-unknown-linux-musl'
      linux4:
        imageName: 'ubuntu-16.04'
        rust_target_run: 'x86_64-unknown-linux-gnu' # i686-unknown-linux-gnu x86_64-unknown-linux-musl i686-unknown-linux-musl'
      linux5:
        imageName: 'ubuntu-16.04'
        rust_target_run: 'x86_64-unknown-linux-gnu' # i686-unknown-linux-gnu x86_64-unknown-linux-musl i686-unknown-linux-musl'
      linux6:
        imageName: 'ubuntu-16.04'
        rust_target_run: 'x86_64-unknown-linux-gnu' # i686-unknown-linux-gnu x86_64-unknown-linux-musl i686-unknown-linux-musl'
      linux7:
        imageName: 'ubuntu-16.04'
        rust_target_run: 'x86_64-unknown-linux-gnu' # i686-unknown-linux-gnu x86_64-unknown-linux-musl i686-unknown-linux-musl'
      linux8:
        imageName: 'ubuntu-16.04'
        rust_target_run: 'x86_64-unknown-linux-gnu' # i686-unknown-linux-gnu x86_64-unknown-linux-musl i686-unknown-linux-musl'
      linux9:
        imageName: 'ubuntu-16.04'
        rust_target_run: 'x86_64-unknown-linux-gnu' # i686-unknown-linux-gnu x86_64-unknown-linux-musl i686-unknown-linux-musl'
