[package]
name = "constellation-internal"
version = "0.1.2"
license = "Apache-2.0"
authors = ["Alec Mocatta <alec@mocatta.net>"]
categories = ["development-tools","network-programming","concurrency","asynchronous"]
keywords = ["constellation","deploy","distributed","cluster"]
description = """
Common components for the `constellation` framework.
"""
repository = "https://github.com/alecmocatta/constellation"
homepage = "https://github.com/alecmocatta/constellation"
documentation = "https://docs.rs/constellation-rs"

[dependencies]
serde_derive = "1.0.59"
serde = "1.0.59"
serde_json = "1.0"
aes_frast = "0.1"
either = {version = "1.5", features = ["serde"]}
ansi_term = "0.11"
rand = "0.5"
bincode = "1.0"
cargo_metadata = {version = "0.6", default-features = false}

[target.'cfg(unix)'.dependencies]
nix = "0.11"

[target.'cfg(windows)'.dependencies]
winapi = {version = "0.3", features = []}
