version: 2
jobs:
  build:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      # - restore_cache:
      #     key: cache
      - run:
          environment:
            TARGET: x86_64-unknown-linux-gnu
          command: |
            ( set -o errexit;set -o pipefail; set -o xtrace;set -o nounset;
              apt update && apt install --yes curl gcc
              curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly
              source $HOME/.cargo/env
              cargo build --verbose --target "$TARGET" --all-targets --all-features
              RUSTFLAGS="-C target-cpu=native" cargo build --verbose --target "$TARGET" --all-targets --all-features --release
              RUST_BACKTRACE=full cargo test --test tester --target "$TARGET" --all-features -- 10
              RUSTFLAGS="-C target-cpu=native" RUST_BACKTRACE=full cargo test --test tester --target "$TARGET" --all-features --release -- 10 --all-features --release
              RUSTFLAGS="-C target-cpu=native" RUST_BACKTRACE=full cargo bench --target "$TARGET" --all-features
              [ ! -d examples ] || for example in examples/*; do example=${example##*/}; (
                RUST_BACKTRACE=full cargo run --target "$TARGET" --example ${example%.*} --all-features
                RUSTFLAGS="-C target-cpu=native" RUST_BACKTRACE=full cargo run --target "$TARGET" --example ${example%.*} --all-features --release
              ); done
            )
      # - save_cache:
      #     key: cache
      #     paths:
      #       - "~/.cargo"
      #       - "./target"
